# Generated by Django 2.2.28 on 2024-12-15 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_delete_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tour',
            old_name='country',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='tour',
            name='days',
        ),
        migrations.RemoveField(
            model_name='tour',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='tour',
            name='start_date',
        ),
    ]
